# Promise
<br/>

### Promise 객체
	- 비동기 작업의 완료 또는 실패를 나타내는 객체.
 	- 비동기 작업을 처리할 때 콜백 지옥 (Callback Hell)을 피하고 코드를 더 간결하고 가독성 있게 만들 수 있다.
	- Promise 객체를 생성할 경우 파라미터로 두 개의 콜백 함수가 들어가며, 
 	  메서드 내부에 성공 시 실행되는 콜백 함수와 실패 시 실행되는 콜백 함수가 들어갈 수 있다. 
<br/>

### Promise 객체는 기본적으로 3가지 중 하나의 상태를 가진다.
	1. pending (준비되지 않은 상태, 대기 중)
	2. fullfilled (비동기 작업이 완료된 상태, 이행됨)
	3. rejected (비동기 작업이 실패된 상태, 거부됨)
 
<br><br>

### 1. Promise 생성
####  - 기본적인 코드의 형태는 [코드 1]과 같으며, [코드 1]에서의 Promise의 state와 result는 [상태 1]과 같다. 
#### [코드 1]
	const promise = new Promise ((resolve, reject) => {
 		// 비동기 작업을 수행하는 코드
   		// ...
		resolve(결과);	// resolve: 성공 시 실행되는 함수
		reject(에러);	// reject: 실패 시 실행되는 함수
	});

#### [상태 1]
- 생성 시: new Promise

| Property | Value |
|---|---|
| state | pending |
| result | undefined |

- 성공 시: resolve(value)

| Property | Value |
|---|---|
| state | fulfilled |
| result | value |

- 실패 시: reject(error)

| Property | Value |
|---|---|
| state | rejected |
| result | Error |

<br><br>
### 2. resolve
#### - 성공 시 코드는 아래의 [코드 2]와 같으며, [코드 2]에서의 Promise의 state와 result는 [상태 2]와 같다.
#### [코드 2]
	const promise = new Promise ((resolve, reject) => {
		setTimeout(() => {
			resolve(‘OK’)
		}, 3000)
	});

#### [상태 2]
| Property | Value |
|---|---|
| state | fulfilled |
| result | ‘OK’ |

<br><br>
### 3. reject
#### - 실패 시 코드는 아래의 [코드 3]과 같으며, [코드 3]에서의 Promise의 state와 result는 [상태 3] 같다.
#### [코드 3]
	const promise = new Promise ((resolve, reject) => {
		setTimeout(() => {
			reject(new Error(‘error’))
		}, 3000)
	});
 
#### [상태 3]
| Property | Value |
|---|---|
| state | rejected |
| result | 'error' |



<br><br>
#### [코드 1]을 .then() 메서드를 통해 아래의 [코드 4-1]과 [코드 4-2]로 나누어 작성할 수 있다. 

#### [코드 4-1]
	const pr = new Promise ((resolve, reject) => {
		setTimeout(() => {
			resolve(‘OK’)
		}, 3000)
	});

#### [코드 4-2]
	pr.then(
		// 이행되었을 때 (fulfilled) 실행
		function(result) {
			console.log(result + ‘ 가지러 가자.’);
	},
		// 거부되었을 때 (rejected) 실행
		function(err) {
			console.log(‘다시 주문해주세요..’);
	});

#### [결과 1]
	OK 가지러 가자.

#### [결과 2]
	다시 주문해주세요..

#### --> [코드 4-1]에서 비동기 작업이 성공적으로 완료되었을 경우 console에 [결과 1]이,
#### [코드 4-2]에서 비동기 작업이 실패하였을 경우 console에 [결과 2]가 출력된다.


<br><br>
#### .catch() 메서드를 통해 에러를 처리할 수 있는데, [코드 5]에서처럼 catch 내부에 reject에 해당하는 콜백 함수를 불러와 코드의 가독성을 증진시킬 수 있다.

#### [코드 5]
	const pr = new Promise ((resolve, reject) => {
		setTimeout( () => {
			resolve(‘ok’)
		}, 3000)
	});
	pr.then(	// 이행되었을 때 (fulfilled) 실행
		function(result) {
			console.log(result + ‘가지러 가자.’);
	}).catch(		// 거부되었을 때 (rejected) 실행
		function(err) {
			console.log(‘다시 주문해주세요..’);
	});

